{
  "created": 1722013179.271529,
  "duration": 7.3797314167022705,
  "exitcode": 1,
  "root": "/home/jsw/mezz/econd-sw/test_mezzanine",
  "environment": {},
  "summary": {
    "error": 15,
    "total": 15,
    "collected": 15
  },
  "collectors": [
    {
      "nodeid": "",
      "outcome": "passed",
      "result": [
        {
          "nodeid": "test_io.py",
          "type": "Module"
        }
      ]
    },
    {
      "nodeid": "test_io.py",
      "outcome": "passed",
      "result": [
        {
          "nodeid": "test_io.py::test_ePortRXPRBS_ECOND[1.08]",
          "type": "Function",
          "lineno": 246
        },
        {
          "nodeid": "test_io.py::test_ePortRXPRBS_ECOND[1.32]",
          "type": "Function",
          "lineno": 246
        },
        {
          "nodeid": "test_io.py::test_ePortRXPRBS_ECOND[1.2]",
          "type": "Function",
          "lineno": 246
        },
        {
          "nodeid": "test_io.py::test_ePortRXPRBS_ECONT[1.08]",
          "type": "Function",
          "lineno": 274
        },
        {
          "nodeid": "test_io.py::test_ePortRXPRBS_ECONT[1.32]",
          "type": "Function",
          "lineno": 274
        },
        {
          "nodeid": "test_io.py::test_ePortRXPRBS_ECONT[1.2]",
          "type": "Function",
          "lineno": 274
        },
        {
          "nodeid": "test_io.py::test_eTX_delayscan_ECOND[1.08]",
          "type": "Function",
          "lineno": 303
        },
        {
          "nodeid": "test_io.py::test_eTX_delayscan_ECOND[1.32]",
          "type": "Function",
          "lineno": 303
        },
        {
          "nodeid": "test_io.py::test_eTX_delayscan_ECOND[1.2]",
          "type": "Function",
          "lineno": 303
        },
        {
          "nodeid": "test_io.py::test_eTX_delayscan_ECONT[1.08]",
          "type": "Function",
          "lineno": 330
        },
        {
          "nodeid": "test_io.py::test_eTX_delayscan_ECONT[1.32]",
          "type": "Function",
          "lineno": 330
        },
        {
          "nodeid": "test_io.py::test_eTX_delayscan_ECONT[1.2]",
          "type": "Function",
          "lineno": 330
        },
        {
          "nodeid": "test_io.py::test_eTx_PRBS7_ECOND[1.08]",
          "type": "Function",
          "lineno": 356
        },
        {
          "nodeid": "test_io.py::test_eTx_PRBS7_ECOND[1.32]",
          "type": "Function",
          "lineno": 356
        },
        {
          "nodeid": "test_io.py::test_eTx_PRBS7_ECOND[1.2]",
          "type": "Function",
          "lineno": 356
        }
      ]
    }
  ],
  "tests": [
    {
      "nodeid": "test_io.py::test_ePortRXPRBS_ECOND[1.08]",
      "lineno": 246,
      "outcome": "error",
      "keywords": [
        "test_ePortRXPRBS_ECOND[1.08]",
        "pytestmark",
        "1.08",
        "ECOND",
        "test_io.py",
        "test_mezzanine"
      ],
      "setup": {
        "duration": 4.22700758100018,
        "outcome": "failed",
        "crash": {
          "path": "zmq/backend/cython/checkrc.pxd",
          "lineno": 20,
          "message": "zmq.error.Again: Resource temporarily unavailable"
        },
        "traceback": [
          {
            "path": "test_io.py",
            "lineno": 14,
            "message": "in set_voltage"
          },
          {
            "path": "../utils/gpibclient.py",
            "lineno": 42,
            "message": "in SetVoltage"
          },
          {
            "path": "../utils/gpibclient.py",
            "lineno": 26,
            "message": "in ReadPower"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 791,
            "message": "in zmq.backend.cython.socket.Socket.recv"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 827,
            "message": "in zmq.backend.cython.socket.Socket.recv"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 191,
            "message": "in zmq.backend.cython.socket._recv_copy"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 186,
            "message": "in zmq.backend.cython.socket._recv_copy"
          },
          {
            "path": "zmq/backend/cython/checkrc.pxd",
            "lineno": 20,
            "message": "in zmq.backend.cython.checkrc._check_rc"
          }
        ],
        "longrepr": "test_io.py:14: in set_voltage\n    gpib_client.SetVoltage(voltage)\n../utils/gpibclient.py:42: in SetVoltage\n    _p,_v,_i  = self.ReadPower()\n../utils/gpibclient.py:26: in ReadPower\n    message = self.socket.recv()\nzmq/backend/cython/socket.pyx:791: in zmq.backend.cython.socket.Socket.recv\n    ???\nzmq/backend/cython/socket.pyx:827: in zmq.backend.cython.socket.Socket.recv\n    ???\nzmq/backend/cython/socket.pyx:191: in zmq.backend.cython.socket._recv_copy\n    ???\nzmq/backend/cython/socket.pyx:186: in zmq.backend.cython.socket._recv_copy\n    ???\nzmq/backend/cython/checkrc.pxd:20: in zmq.backend.cython.checkrc._check_rc\n    ???\nE   zmq.error.Again: Resource temporarily unavailable"
      },
      "teardown": {
        "duration": 0.001247426999725576,
        "outcome": "passed"
      }
    },
    {
      "nodeid": "test_io.py::test_ePortRXPRBS_ECONT[1.08]",
      "lineno": 274,
      "outcome": "error",
      "keywords": [
        "test_ePortRXPRBS_ECONT[1.08]",
        "pytestmark",
        "1.08",
        "ECONT",
        "test_io.py",
        "test_mezzanine"
      ],
      "setup": {
        "duration": 0.36743491899960645,
        "outcome": "failed",
        "crash": {
          "path": "zmq/backend/cython/checkrc.pxd",
          "lineno": 20,
          "message": "zmq.error.Again: Resource temporarily unavailable"
        },
        "traceback": [
          {
            "path": "test_io.py",
            "lineno": 14,
            "message": "in set_voltage"
          },
          {
            "path": "../utils/gpibclient.py",
            "lineno": 42,
            "message": "in SetVoltage"
          },
          {
            "path": "../utils/gpibclient.py",
            "lineno": 26,
            "message": "in ReadPower"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 791,
            "message": "in zmq.backend.cython.socket.Socket.recv"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 827,
            "message": "in zmq.backend.cython.socket.Socket.recv"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 191,
            "message": "in zmq.backend.cython.socket._recv_copy"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 186,
            "message": "in zmq.backend.cython.socket._recv_copy"
          },
          {
            "path": "zmq/backend/cython/checkrc.pxd",
            "lineno": 20,
            "message": "in zmq.backend.cython.checkrc._check_rc"
          }
        ],
        "longrepr": "test_io.py:14: in set_voltage\n    gpib_client.SetVoltage(voltage)\n../utils/gpibclient.py:42: in SetVoltage\n    _p,_v,_i  = self.ReadPower()\n../utils/gpibclient.py:26: in ReadPower\n    message = self.socket.recv()\nzmq/backend/cython/socket.pyx:791: in zmq.backend.cython.socket.Socket.recv\n    ???\nzmq/backend/cython/socket.pyx:827: in zmq.backend.cython.socket.Socket.recv\n    ???\nzmq/backend/cython/socket.pyx:191: in zmq.backend.cython.socket._recv_copy\n    ???\nzmq/backend/cython/socket.pyx:186: in zmq.backend.cython.socket._recv_copy\n    ???\nzmq/backend/cython/checkrc.pxd:20: in zmq.backend.cython.checkrc._check_rc\n    ???\nE   zmq.error.Again: Resource temporarily unavailable"
      },
      "teardown": {
        "duration": 0.0012435279995770543,
        "outcome": "passed"
      }
    },
    {
      "nodeid": "test_io.py::test_eTX_delayscan_ECOND[1.08]",
      "lineno": 303,
      "outcome": "error",
      "keywords": [
        "test_eTX_delayscan_ECOND[1.08]",
        "pytestmark",
        "1.08",
        "ECOND",
        "test_io.py",
        "test_mezzanine"
      ],
      "setup": {
        "duration": 0.011114074999568402,
        "outcome": "failed",
        "crash": {
          "path": "zmq/backend/cython/checkrc.pxd",
          "lineno": 20,
          "message": "zmq.error.Again: Resource temporarily unavailable"
        },
        "traceback": [
          {
            "path": "test_io.py",
            "lineno": 14,
            "message": "in set_voltage"
          },
          {
            "path": "../utils/gpibclient.py",
            "lineno": 42,
            "message": "in SetVoltage"
          },
          {
            "path": "../utils/gpibclient.py",
            "lineno": 26,
            "message": "in ReadPower"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 791,
            "message": "in zmq.backend.cython.socket.Socket.recv"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 827,
            "message": "in zmq.backend.cython.socket.Socket.recv"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 191,
            "message": "in zmq.backend.cython.socket._recv_copy"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 186,
            "message": "in zmq.backend.cython.socket._recv_copy"
          },
          {
            "path": "zmq/backend/cython/checkrc.pxd",
            "lineno": 20,
            "message": "in zmq.backend.cython.checkrc._check_rc"
          }
        ],
        "longrepr": "test_io.py:14: in set_voltage\n    gpib_client.SetVoltage(voltage)\n../utils/gpibclient.py:42: in SetVoltage\n    _p,_v,_i  = self.ReadPower()\n../utils/gpibclient.py:26: in ReadPower\n    message = self.socket.recv()\nzmq/backend/cython/socket.pyx:791: in zmq.backend.cython.socket.Socket.recv\n    ???\nzmq/backend/cython/socket.pyx:827: in zmq.backend.cython.socket.Socket.recv\n    ???\nzmq/backend/cython/socket.pyx:191: in zmq.backend.cython.socket._recv_copy\n    ???\nzmq/backend/cython/socket.pyx:186: in zmq.backend.cython.socket._recv_copy\n    ???\nzmq/backend/cython/checkrc.pxd:20: in zmq.backend.cython.checkrc._check_rc\n    ???\nE   zmq.error.Again: Resource temporarily unavailable"
      },
      "teardown": {
        "duration": 0.0012336570007391856,
        "outcome": "passed"
      }
    },
    {
      "nodeid": "test_io.py::test_eTX_delayscan_ECONT[1.08]",
      "lineno": 330,
      "outcome": "error",
      "keywords": [
        "test_eTX_delayscan_ECONT[1.08]",
        "pytestmark",
        "1.08",
        "ECONT",
        "test_io.py",
        "test_mezzanine"
      ],
      "setup": {
        "duration": 0.004361706000054255,
        "outcome": "failed",
        "crash": {
          "path": "zmq/backend/cython/checkrc.pxd",
          "lineno": 20,
          "message": "zmq.error.Again: Resource temporarily unavailable"
        },
        "traceback": [
          {
            "path": "test_io.py",
            "lineno": 14,
            "message": "in set_voltage"
          },
          {
            "path": "../utils/gpibclient.py",
            "lineno": 42,
            "message": "in SetVoltage"
          },
          {
            "path": "../utils/gpibclient.py",
            "lineno": 26,
            "message": "in ReadPower"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 791,
            "message": "in zmq.backend.cython.socket.Socket.recv"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 827,
            "message": "in zmq.backend.cython.socket.Socket.recv"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 191,
            "message": "in zmq.backend.cython.socket._recv_copy"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 186,
            "message": "in zmq.backend.cython.socket._recv_copy"
          },
          {
            "path": "zmq/backend/cython/checkrc.pxd",
            "lineno": 20,
            "message": "in zmq.backend.cython.checkrc._check_rc"
          }
        ],
        "longrepr": "test_io.py:14: in set_voltage\n    gpib_client.SetVoltage(voltage)\n../utils/gpibclient.py:42: in SetVoltage\n    _p,_v,_i  = self.ReadPower()\n../utils/gpibclient.py:26: in ReadPower\n    message = self.socket.recv()\nzmq/backend/cython/socket.pyx:791: in zmq.backend.cython.socket.Socket.recv\n    ???\nzmq/backend/cython/socket.pyx:827: in zmq.backend.cython.socket.Socket.recv\n    ???\nzmq/backend/cython/socket.pyx:191: in zmq.backend.cython.socket._recv_copy\n    ???\nzmq/backend/cython/socket.pyx:186: in zmq.backend.cython.socket._recv_copy\n    ???\nzmq/backend/cython/checkrc.pxd:20: in zmq.backend.cython.checkrc._check_rc\n    ???\nE   zmq.error.Again: Resource temporarily unavailable"
      },
      "teardown": {
        "duration": 0.0012273570000616019,
        "outcome": "passed"
      }
    },
    {
      "nodeid": "test_io.py::test_eTx_PRBS7_ECOND[1.08]",
      "lineno": 356,
      "outcome": "error",
      "keywords": [
        "test_eTx_PRBS7_ECOND[1.08]",
        "pytestmark",
        "1.08",
        "ECOND",
        "test_io.py",
        "test_mezzanine"
      ],
      "setup": {
        "duration": 0.005372098000407277,
        "outcome": "failed",
        "crash": {
          "path": "zmq/backend/cython/checkrc.pxd",
          "lineno": 20,
          "message": "zmq.error.Again: Resource temporarily unavailable"
        },
        "traceback": [
          {
            "path": "test_io.py",
            "lineno": 14,
            "message": "in set_voltage"
          },
          {
            "path": "../utils/gpibclient.py",
            "lineno": 42,
            "message": "in SetVoltage"
          },
          {
            "path": "../utils/gpibclient.py",
            "lineno": 26,
            "message": "in ReadPower"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 791,
            "message": "in zmq.backend.cython.socket.Socket.recv"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 827,
            "message": "in zmq.backend.cython.socket.Socket.recv"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 191,
            "message": "in zmq.backend.cython.socket._recv_copy"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 186,
            "message": "in zmq.backend.cython.socket._recv_copy"
          },
          {
            "path": "zmq/backend/cython/checkrc.pxd",
            "lineno": 20,
            "message": "in zmq.backend.cython.checkrc._check_rc"
          }
        ],
        "longrepr": "test_io.py:14: in set_voltage\n    gpib_client.SetVoltage(voltage)\n../utils/gpibclient.py:42: in SetVoltage\n    _p,_v,_i  = self.ReadPower()\n../utils/gpibclient.py:26: in ReadPower\n    message = self.socket.recv()\nzmq/backend/cython/socket.pyx:791: in zmq.backend.cython.socket.Socket.recv\n    ???\nzmq/backend/cython/socket.pyx:827: in zmq.backend.cython.socket.Socket.recv\n    ???\nzmq/backend/cython/socket.pyx:191: in zmq.backend.cython.socket._recv_copy\n    ???\nzmq/backend/cython/socket.pyx:186: in zmq.backend.cython.socket._recv_copy\n    ???\nzmq/backend/cython/checkrc.pxd:20: in zmq.backend.cython.checkrc._check_rc\n    ???\nE   zmq.error.Again: Resource temporarily unavailable"
      },
      "teardown": {
        "duration": 0.001236537999830034,
        "outcome": "passed"
      }
    },
    {
      "nodeid": "test_io.py::test_ePortRXPRBS_ECOND[1.32]",
      "lineno": 246,
      "outcome": "error",
      "keywords": [
        "test_ePortRXPRBS_ECOND[1.32]",
        "pytestmark",
        "1.32",
        "ECOND",
        "test_io.py",
        "test_mezzanine"
      ],
      "setup": {
        "duration": 0.0077889819995107246,
        "outcome": "failed",
        "crash": {
          "path": "zmq/backend/cython/checkrc.pxd",
          "lineno": 26,
          "message": "zmq.error.ZMQError: Operation cannot be accomplished in current state"
        },
        "traceback": [
          {
            "path": "test_io.py",
            "lineno": 14,
            "message": "in set_voltage"
          },
          {
            "path": "../utils/gpibclient.py",
            "lineno": 40,
            "message": "in SetVoltage"
          },
          {
            "path": "/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py",
            "lineno": 568,
            "message": "in send_string"
          },
          {
            "path": "/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py",
            "lineno": 400,
            "message": "in send"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 728,
            "message": "in zmq.backend.cython.socket.Socket.send"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 775,
            "message": "in zmq.backend.cython.socket.Socket.send"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 247,
            "message": "in zmq.backend.cython.socket._send_copy"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 242,
            "message": "in zmq.backend.cython.socket._send_copy"
          },
          {
            "path": "zmq/backend/cython/checkrc.pxd",
            "lineno": 26,
            "message": "in zmq.backend.cython.checkrc._check_rc"
          }
        ],
        "longrepr": "test_io.py:14: in set_voltage\n    gpib_client.SetVoltage(voltage)\n../utils/gpibclient.py:40: in SetVoltage\n    self.socket.send_string(f'{self.ip}:::SetVoltage:::{v}')\n/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py:568: in send_string\n    return self.send(u.encode(encoding), flags=flags, copy=copy, **kwargs)\n/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py:400: in send\n    return super(Socket, self).send(data, flags=flags, copy=copy, track=track)\nzmq/backend/cython/socket.pyx:728: in zmq.backend.cython.socket.Socket.send\n    ???\nzmq/backend/cython/socket.pyx:775: in zmq.backend.cython.socket.Socket.send\n    ???\nzmq/backend/cython/socket.pyx:247: in zmq.backend.cython.socket._send_copy\n    ???\nzmq/backend/cython/socket.pyx:242: in zmq.backend.cython.socket._send_copy\n    ???\nzmq/backend/cython/checkrc.pxd:26: in zmq.backend.cython.checkrc._check_rc\n    ???\nE   zmq.error.ZMQError: Operation cannot be accomplished in current state"
      },
      "teardown": {
        "duration": 0.0012806979993911227,
        "outcome": "passed"
      }
    },
    {
      "nodeid": "test_io.py::test_ePortRXPRBS_ECONT[1.32]",
      "lineno": 274,
      "outcome": "error",
      "keywords": [
        "test_ePortRXPRBS_ECONT[1.32]",
        "pytestmark",
        "1.32",
        "ECONT",
        "test_io.py",
        "test_mezzanine"
      ],
      "setup": {
        "duration": 0.006789269999899261,
        "outcome": "failed",
        "crash": {
          "path": "zmq/backend/cython/checkrc.pxd",
          "lineno": 26,
          "message": "zmq.error.ZMQError: Operation cannot be accomplished in current state"
        },
        "traceback": [
          {
            "path": "test_io.py",
            "lineno": 14,
            "message": "in set_voltage"
          },
          {
            "path": "../utils/gpibclient.py",
            "lineno": 40,
            "message": "in SetVoltage"
          },
          {
            "path": "/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py",
            "lineno": 568,
            "message": "in send_string"
          },
          {
            "path": "/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py",
            "lineno": 400,
            "message": "in send"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 728,
            "message": "in zmq.backend.cython.socket.Socket.send"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 775,
            "message": "in zmq.backend.cython.socket.Socket.send"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 247,
            "message": "in zmq.backend.cython.socket._send_copy"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 242,
            "message": "in zmq.backend.cython.socket._send_copy"
          },
          {
            "path": "zmq/backend/cython/checkrc.pxd",
            "lineno": 26,
            "message": "in zmq.backend.cython.checkrc._check_rc"
          }
        ],
        "longrepr": "test_io.py:14: in set_voltage\n    gpib_client.SetVoltage(voltage)\n../utils/gpibclient.py:40: in SetVoltage\n    self.socket.send_string(f'{self.ip}:::SetVoltage:::{v}')\n/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py:568: in send_string\n    return self.send(u.encode(encoding), flags=flags, copy=copy, **kwargs)\n/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py:400: in send\n    return super(Socket, self).send(data, flags=flags, copy=copy, track=track)\nzmq/backend/cython/socket.pyx:728: in zmq.backend.cython.socket.Socket.send\n    ???\nzmq/backend/cython/socket.pyx:775: in zmq.backend.cython.socket.Socket.send\n    ???\nzmq/backend/cython/socket.pyx:247: in zmq.backend.cython.socket._send_copy\n    ???\nzmq/backend/cython/socket.pyx:242: in zmq.backend.cython.socket._send_copy\n    ???\nzmq/backend/cython/checkrc.pxd:26: in zmq.backend.cython.checkrc._check_rc\n    ???\nE   zmq.error.ZMQError: Operation cannot be accomplished in current state"
      },
      "teardown": {
        "duration": 0.0012686680001934292,
        "outcome": "passed"
      }
    },
    {
      "nodeid": "test_io.py::test_eTX_delayscan_ECOND[1.32]",
      "lineno": 303,
      "outcome": "error",
      "keywords": [
        "test_eTX_delayscan_ECOND[1.32]",
        "pytestmark",
        "1.32",
        "ECOND",
        "test_io.py",
        "test_mezzanine"
      ],
      "setup": {
        "duration": 0.004590102000292973,
        "outcome": "failed",
        "crash": {
          "path": "zmq/backend/cython/checkrc.pxd",
          "lineno": 26,
          "message": "zmq.error.ZMQError: Operation cannot be accomplished in current state"
        },
        "traceback": [
          {
            "path": "test_io.py",
            "lineno": 14,
            "message": "in set_voltage"
          },
          {
            "path": "../utils/gpibclient.py",
            "lineno": 40,
            "message": "in SetVoltage"
          },
          {
            "path": "/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py",
            "lineno": 568,
            "message": "in send_string"
          },
          {
            "path": "/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py",
            "lineno": 400,
            "message": "in send"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 728,
            "message": "in zmq.backend.cython.socket.Socket.send"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 775,
            "message": "in zmq.backend.cython.socket.Socket.send"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 247,
            "message": "in zmq.backend.cython.socket._send_copy"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 242,
            "message": "in zmq.backend.cython.socket._send_copy"
          },
          {
            "path": "zmq/backend/cython/checkrc.pxd",
            "lineno": 26,
            "message": "in zmq.backend.cython.checkrc._check_rc"
          }
        ],
        "longrepr": "test_io.py:14: in set_voltage\n    gpib_client.SetVoltage(voltage)\n../utils/gpibclient.py:40: in SetVoltage\n    self.socket.send_string(f'{self.ip}:::SetVoltage:::{v}')\n/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py:568: in send_string\n    return self.send(u.encode(encoding), flags=flags, copy=copy, **kwargs)\n/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py:400: in send\n    return super(Socket, self).send(data, flags=flags, copy=copy, track=track)\nzmq/backend/cython/socket.pyx:728: in zmq.backend.cython.socket.Socket.send\n    ???\nzmq/backend/cython/socket.pyx:775: in zmq.backend.cython.socket.Socket.send\n    ???\nzmq/backend/cython/socket.pyx:247: in zmq.backend.cython.socket._send_copy\n    ???\nzmq/backend/cython/socket.pyx:242: in zmq.backend.cython.socket._send_copy\n    ???\nzmq/backend/cython/checkrc.pxd:26: in zmq.backend.cython.checkrc._check_rc\n    ???\nE   zmq.error.ZMQError: Operation cannot be accomplished in current state"
      },
      "teardown": {
        "duration": 0.0012354270002106205,
        "outcome": "passed"
      }
    },
    {
      "nodeid": "test_io.py::test_eTX_delayscan_ECONT[1.32]",
      "lineno": 330,
      "outcome": "error",
      "keywords": [
        "test_eTX_delayscan_ECONT[1.32]",
        "pytestmark",
        "1.32",
        "ECONT",
        "test_io.py",
        "test_mezzanine"
      ],
      "setup": {
        "duration": 0.004358406000392279,
        "outcome": "failed",
        "crash": {
          "path": "zmq/backend/cython/checkrc.pxd",
          "lineno": 26,
          "message": "zmq.error.ZMQError: Operation cannot be accomplished in current state"
        },
        "traceback": [
          {
            "path": "test_io.py",
            "lineno": 14,
            "message": "in set_voltage"
          },
          {
            "path": "../utils/gpibclient.py",
            "lineno": 40,
            "message": "in SetVoltage"
          },
          {
            "path": "/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py",
            "lineno": 568,
            "message": "in send_string"
          },
          {
            "path": "/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py",
            "lineno": 400,
            "message": "in send"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 728,
            "message": "in zmq.backend.cython.socket.Socket.send"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 775,
            "message": "in zmq.backend.cython.socket.Socket.send"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 247,
            "message": "in zmq.backend.cython.socket._send_copy"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 242,
            "message": "in zmq.backend.cython.socket._send_copy"
          },
          {
            "path": "zmq/backend/cython/checkrc.pxd",
            "lineno": 26,
            "message": "in zmq.backend.cython.checkrc._check_rc"
          }
        ],
        "longrepr": "test_io.py:14: in set_voltage\n    gpib_client.SetVoltage(voltage)\n../utils/gpibclient.py:40: in SetVoltage\n    self.socket.send_string(f'{self.ip}:::SetVoltage:::{v}')\n/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py:568: in send_string\n    return self.send(u.encode(encoding), flags=flags, copy=copy, **kwargs)\n/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py:400: in send\n    return super(Socket, self).send(data, flags=flags, copy=copy, track=track)\nzmq/backend/cython/socket.pyx:728: in zmq.backend.cython.socket.Socket.send\n    ???\nzmq/backend/cython/socket.pyx:775: in zmq.backend.cython.socket.Socket.send\n    ???\nzmq/backend/cython/socket.pyx:247: in zmq.backend.cython.socket._send_copy\n    ???\nzmq/backend/cython/socket.pyx:242: in zmq.backend.cython.socket._send_copy\n    ???\nzmq/backend/cython/checkrc.pxd:26: in zmq.backend.cython.checkrc._check_rc\n    ???\nE   zmq.error.ZMQError: Operation cannot be accomplished in current state"
      },
      "teardown": {
        "duration": 0.0012385780000840896,
        "outcome": "passed"
      }
    },
    {
      "nodeid": "test_io.py::test_eTx_PRBS7_ECOND[1.32]",
      "lineno": 356,
      "outcome": "error",
      "keywords": [
        "test_eTx_PRBS7_ECOND[1.32]",
        "pytestmark",
        "1.32",
        "ECOND",
        "test_io.py",
        "test_mezzanine"
      ],
      "setup": {
        "duration": 0.004570930999761913,
        "outcome": "failed",
        "crash": {
          "path": "zmq/backend/cython/checkrc.pxd",
          "lineno": 26,
          "message": "zmq.error.ZMQError: Operation cannot be accomplished in current state"
        },
        "traceback": [
          {
            "path": "test_io.py",
            "lineno": 14,
            "message": "in set_voltage"
          },
          {
            "path": "../utils/gpibclient.py",
            "lineno": 40,
            "message": "in SetVoltage"
          },
          {
            "path": "/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py",
            "lineno": 568,
            "message": "in send_string"
          },
          {
            "path": "/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py",
            "lineno": 400,
            "message": "in send"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 728,
            "message": "in zmq.backend.cython.socket.Socket.send"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 775,
            "message": "in zmq.backend.cython.socket.Socket.send"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 247,
            "message": "in zmq.backend.cython.socket._send_copy"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 242,
            "message": "in zmq.backend.cython.socket._send_copy"
          },
          {
            "path": "zmq/backend/cython/checkrc.pxd",
            "lineno": 26,
            "message": "in zmq.backend.cython.checkrc._check_rc"
          }
        ],
        "longrepr": "test_io.py:14: in set_voltage\n    gpib_client.SetVoltage(voltage)\n../utils/gpibclient.py:40: in SetVoltage\n    self.socket.send_string(f'{self.ip}:::SetVoltage:::{v}')\n/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py:568: in send_string\n    return self.send(u.encode(encoding), flags=flags, copy=copy, **kwargs)\n/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py:400: in send\n    return super(Socket, self).send(data, flags=flags, copy=copy, track=track)\nzmq/backend/cython/socket.pyx:728: in zmq.backend.cython.socket.Socket.send\n    ???\nzmq/backend/cython/socket.pyx:775: in zmq.backend.cython.socket.Socket.send\n    ???\nzmq/backend/cython/socket.pyx:247: in zmq.backend.cython.socket._send_copy\n    ???\nzmq/backend/cython/socket.pyx:242: in zmq.backend.cython.socket._send_copy\n    ???\nzmq/backend/cython/checkrc.pxd:26: in zmq.backend.cython.checkrc._check_rc\n    ???\nE   zmq.error.ZMQError: Operation cannot be accomplished in current state"
      },
      "teardown": {
        "duration": 0.0012468280001485255,
        "outcome": "passed"
      }
    },
    {
      "nodeid": "test_io.py::test_ePortRXPRBS_ECOND[1.2]",
      "lineno": 246,
      "outcome": "error",
      "keywords": [
        "test_ePortRXPRBS_ECOND[1.2]",
        "pytestmark",
        "1.2",
        "ECOND",
        "test_io.py",
        "test_mezzanine"
      ],
      "setup": {
        "duration": 0.007711938999818813,
        "outcome": "failed",
        "crash": {
          "path": "zmq/backend/cython/checkrc.pxd",
          "lineno": 26,
          "message": "zmq.error.ZMQError: Operation cannot be accomplished in current state"
        },
        "traceback": [
          {
            "path": "test_io.py",
            "lineno": 14,
            "message": "in set_voltage"
          },
          {
            "path": "../utils/gpibclient.py",
            "lineno": 40,
            "message": "in SetVoltage"
          },
          {
            "path": "/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py",
            "lineno": 568,
            "message": "in send_string"
          },
          {
            "path": "/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py",
            "lineno": 400,
            "message": "in send"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 728,
            "message": "in zmq.backend.cython.socket.Socket.send"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 775,
            "message": "in zmq.backend.cython.socket.Socket.send"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 247,
            "message": "in zmq.backend.cython.socket._send_copy"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 242,
            "message": "in zmq.backend.cython.socket._send_copy"
          },
          {
            "path": "zmq/backend/cython/checkrc.pxd",
            "lineno": 26,
            "message": "in zmq.backend.cython.checkrc._check_rc"
          }
        ],
        "longrepr": "test_io.py:14: in set_voltage\n    gpib_client.SetVoltage(voltage)\n../utils/gpibclient.py:40: in SetVoltage\n    self.socket.send_string(f'{self.ip}:::SetVoltage:::{v}')\n/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py:568: in send_string\n    return self.send(u.encode(encoding), flags=flags, copy=copy, **kwargs)\n/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py:400: in send\n    return super(Socket, self).send(data, flags=flags, copy=copy, track=track)\nzmq/backend/cython/socket.pyx:728: in zmq.backend.cython.socket.Socket.send\n    ???\nzmq/backend/cython/socket.pyx:775: in zmq.backend.cython.socket.Socket.send\n    ???\nzmq/backend/cython/socket.pyx:247: in zmq.backend.cython.socket._send_copy\n    ???\nzmq/backend/cython/socket.pyx:242: in zmq.backend.cython.socket._send_copy\n    ???\nzmq/backend/cython/checkrc.pxd:26: in zmq.backend.cython.checkrc._check_rc\n    ???\nE   zmq.error.ZMQError: Operation cannot be accomplished in current state"
      },
      "teardown": {
        "duration": 0.0012506679995567538,
        "outcome": "passed"
      }
    },
    {
      "nodeid": "test_io.py::test_ePortRXPRBS_ECONT[1.2]",
      "lineno": 274,
      "outcome": "error",
      "keywords": [
        "test_ePortRXPRBS_ECONT[1.2]",
        "pytestmark",
        "1.2",
        "ECONT",
        "test_io.py",
        "test_mezzanine"
      ],
      "setup": {
        "duration": 0.0063154090003081365,
        "outcome": "failed",
        "crash": {
          "path": "zmq/backend/cython/checkrc.pxd",
          "lineno": 26,
          "message": "zmq.error.ZMQError: Operation cannot be accomplished in current state"
        },
        "traceback": [
          {
            "path": "test_io.py",
            "lineno": 14,
            "message": "in set_voltage"
          },
          {
            "path": "../utils/gpibclient.py",
            "lineno": 40,
            "message": "in SetVoltage"
          },
          {
            "path": "/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py",
            "lineno": 568,
            "message": "in send_string"
          },
          {
            "path": "/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py",
            "lineno": 400,
            "message": "in send"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 728,
            "message": "in zmq.backend.cython.socket.Socket.send"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 775,
            "message": "in zmq.backend.cython.socket.Socket.send"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 247,
            "message": "in zmq.backend.cython.socket._send_copy"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 242,
            "message": "in zmq.backend.cython.socket._send_copy"
          },
          {
            "path": "zmq/backend/cython/checkrc.pxd",
            "lineno": 26,
            "message": "in zmq.backend.cython.checkrc._check_rc"
          }
        ],
        "longrepr": "test_io.py:14: in set_voltage\n    gpib_client.SetVoltage(voltage)\n../utils/gpibclient.py:40: in SetVoltage\n    self.socket.send_string(f'{self.ip}:::SetVoltage:::{v}')\n/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py:568: in send_string\n    return self.send(u.encode(encoding), flags=flags, copy=copy, **kwargs)\n/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py:400: in send\n    return super(Socket, self).send(data, flags=flags, copy=copy, track=track)\nzmq/backend/cython/socket.pyx:728: in zmq.backend.cython.socket.Socket.send\n    ???\nzmq/backend/cython/socket.pyx:775: in zmq.backend.cython.socket.Socket.send\n    ???\nzmq/backend/cython/socket.pyx:247: in zmq.backend.cython.socket._send_copy\n    ???\nzmq/backend/cython/socket.pyx:242: in zmq.backend.cython.socket._send_copy\n    ???\nzmq/backend/cython/checkrc.pxd:26: in zmq.backend.cython.checkrc._check_rc\n    ???\nE   zmq.error.ZMQError: Operation cannot be accomplished in current state"
      },
      "teardown": {
        "duration": 0.0012514179998106556,
        "outcome": "passed"
      }
    },
    {
      "nodeid": "test_io.py::test_eTX_delayscan_ECOND[1.2]",
      "lineno": 303,
      "outcome": "error",
      "keywords": [
        "test_eTX_delayscan_ECOND[1.2]",
        "pytestmark",
        "1.2",
        "ECOND",
        "test_io.py",
        "test_mezzanine"
      ],
      "setup": {
        "duration": 0.004604951000146684,
        "outcome": "failed",
        "crash": {
          "path": "zmq/backend/cython/checkrc.pxd",
          "lineno": 26,
          "message": "zmq.error.ZMQError: Operation cannot be accomplished in current state"
        },
        "traceback": [
          {
            "path": "test_io.py",
            "lineno": 14,
            "message": "in set_voltage"
          },
          {
            "path": "../utils/gpibclient.py",
            "lineno": 40,
            "message": "in SetVoltage"
          },
          {
            "path": "/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py",
            "lineno": 568,
            "message": "in send_string"
          },
          {
            "path": "/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py",
            "lineno": 400,
            "message": "in send"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 728,
            "message": "in zmq.backend.cython.socket.Socket.send"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 775,
            "message": "in zmq.backend.cython.socket.Socket.send"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 247,
            "message": "in zmq.backend.cython.socket._send_copy"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 242,
            "message": "in zmq.backend.cython.socket._send_copy"
          },
          {
            "path": "zmq/backend/cython/checkrc.pxd",
            "lineno": 26,
            "message": "in zmq.backend.cython.checkrc._check_rc"
          }
        ],
        "longrepr": "test_io.py:14: in set_voltage\n    gpib_client.SetVoltage(voltage)\n../utils/gpibclient.py:40: in SetVoltage\n    self.socket.send_string(f'{self.ip}:::SetVoltage:::{v}')\n/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py:568: in send_string\n    return self.send(u.encode(encoding), flags=flags, copy=copy, **kwargs)\n/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py:400: in send\n    return super(Socket, self).send(data, flags=flags, copy=copy, track=track)\nzmq/backend/cython/socket.pyx:728: in zmq.backend.cython.socket.Socket.send\n    ???\nzmq/backend/cython/socket.pyx:775: in zmq.backend.cython.socket.Socket.send\n    ???\nzmq/backend/cython/socket.pyx:247: in zmq.backend.cython.socket._send_copy\n    ???\nzmq/backend/cython/socket.pyx:242: in zmq.backend.cython.socket._send_copy\n    ???\nzmq/backend/cython/checkrc.pxd:26: in zmq.backend.cython.checkrc._check_rc\n    ???\nE   zmq.error.ZMQError: Operation cannot be accomplished in current state"
      },
      "teardown": {
        "duration": 0.0012384870005917037,
        "outcome": "passed"
      }
    },
    {
      "nodeid": "test_io.py::test_eTX_delayscan_ECONT[1.2]",
      "lineno": 330,
      "outcome": "error",
      "keywords": [
        "test_eTX_delayscan_ECONT[1.2]",
        "pytestmark",
        "1.2",
        "ECONT",
        "test_io.py",
        "test_mezzanine"
      ],
      "setup": {
        "duration": 0.004373345999738376,
        "outcome": "failed",
        "crash": {
          "path": "zmq/backend/cython/checkrc.pxd",
          "lineno": 26,
          "message": "zmq.error.ZMQError: Operation cannot be accomplished in current state"
        },
        "traceback": [
          {
            "path": "test_io.py",
            "lineno": 14,
            "message": "in set_voltage"
          },
          {
            "path": "../utils/gpibclient.py",
            "lineno": 40,
            "message": "in SetVoltage"
          },
          {
            "path": "/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py",
            "lineno": 568,
            "message": "in send_string"
          },
          {
            "path": "/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py",
            "lineno": 400,
            "message": "in send"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 728,
            "message": "in zmq.backend.cython.socket.Socket.send"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 775,
            "message": "in zmq.backend.cython.socket.Socket.send"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 247,
            "message": "in zmq.backend.cython.socket._send_copy"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 242,
            "message": "in zmq.backend.cython.socket._send_copy"
          },
          {
            "path": "zmq/backend/cython/checkrc.pxd",
            "lineno": 26,
            "message": "in zmq.backend.cython.checkrc._check_rc"
          }
        ],
        "longrepr": "test_io.py:14: in set_voltage\n    gpib_client.SetVoltage(voltage)\n../utils/gpibclient.py:40: in SetVoltage\n    self.socket.send_string(f'{self.ip}:::SetVoltage:::{v}')\n/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py:568: in send_string\n    return self.send(u.encode(encoding), flags=flags, copy=copy, **kwargs)\n/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py:400: in send\n    return super(Socket, self).send(data, flags=flags, copy=copy, track=track)\nzmq/backend/cython/socket.pyx:728: in zmq.backend.cython.socket.Socket.send\n    ???\nzmq/backend/cython/socket.pyx:775: in zmq.backend.cython.socket.Socket.send\n    ???\nzmq/backend/cython/socket.pyx:247: in zmq.backend.cython.socket._send_copy\n    ???\nzmq/backend/cython/socket.pyx:242: in zmq.backend.cython.socket._send_copy\n    ???\nzmq/backend/cython/checkrc.pxd:26: in zmq.backend.cython.checkrc._check_rc\n    ???\nE   zmq.error.ZMQError: Operation cannot be accomplished in current state"
      },
      "teardown": {
        "duration": 0.001246226999683131,
        "outcome": "passed"
      }
    },
    {
      "nodeid": "test_io.py::test_eTx_PRBS7_ECOND[1.2]",
      "lineno": 356,
      "outcome": "error",
      "keywords": [
        "test_eTx_PRBS7_ECOND[1.2]",
        "pytestmark",
        "1.2",
        "ECOND",
        "test_io.py",
        "test_mezzanine"
      ],
      "setup": {
        "duration": 0.004571619999296672,
        "outcome": "failed",
        "crash": {
          "path": "zmq/backend/cython/checkrc.pxd",
          "lineno": 26,
          "message": "zmq.error.ZMQError: Operation cannot be accomplished in current state"
        },
        "traceback": [
          {
            "path": "test_io.py",
            "lineno": 14,
            "message": "in set_voltage"
          },
          {
            "path": "../utils/gpibclient.py",
            "lineno": 40,
            "message": "in SetVoltage"
          },
          {
            "path": "/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py",
            "lineno": 568,
            "message": "in send_string"
          },
          {
            "path": "/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py",
            "lineno": 400,
            "message": "in send"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 728,
            "message": "in zmq.backend.cython.socket.Socket.send"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 775,
            "message": "in zmq.backend.cython.socket.Socket.send"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 247,
            "message": "in zmq.backend.cython.socket._send_copy"
          },
          {
            "path": "zmq/backend/cython/socket.pyx",
            "lineno": 242,
            "message": "in zmq.backend.cython.socket._send_copy"
          },
          {
            "path": "zmq/backend/cython/checkrc.pxd",
            "lineno": 26,
            "message": "in zmq.backend.cython.checkrc._check_rc"
          }
        ],
        "longrepr": "test_io.py:14: in set_voltage\n    gpib_client.SetVoltage(voltage)\n../utils/gpibclient.py:40: in SetVoltage\n    self.socket.send_string(f'{self.ip}:::SetVoltage:::{v}')\n/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py:568: in send_string\n    return self.send(u.encode(encoding), flags=flags, copy=copy, **kwargs)\n/usr/local/lib64/python3.9/site-packages/zmq/sugar/socket.py:400: in send\n    return super(Socket, self).send(data, flags=flags, copy=copy, track=track)\nzmq/backend/cython/socket.pyx:728: in zmq.backend.cython.socket.Socket.send\n    ???\nzmq/backend/cython/socket.pyx:775: in zmq.backend.cython.socket.Socket.send\n    ???\nzmq/backend/cython/socket.pyx:247: in zmq.backend.cython.socket._send_copy\n    ???\nzmq/backend/cython/socket.pyx:242: in zmq.backend.cython.socket._send_copy\n    ???\nzmq/backend/cython/checkrc.pxd:26: in zmq.backend.cython.checkrc._check_rc\n    ???\nE   zmq.error.ZMQError: Operation cannot be accomplished in current state"
      },
      "teardown": {
        "duration": 0.0012453580002329545,
        "outcome": "passed"
      }
    }
  ],
  "FPGA-hexa-IP": "11",
  "branch": "DN_CMtester_IO",
  "commit_hash": "4f4f43d62e25add927a484f024c3e2e08d3482d8",
  "remote_url": "ssh://git@gitlab.cern.ch:7999/hgcal-daq-sw/econd-sw.git",
  "status": "M common_pytest/fixtures.py\u0000 M gpib_controls\u0000 M test_mezzanine/conftest.py\u0000 M test_mezzanine/pytest.ini\u0000 M test_mezzanine/test_io.py\u0000 M utils/gpibclient.py\u0000?? econ_i2c.py.orig\u0000?? test_mezzanine/tmp.py\u0000?? test_radiation/conftest.py.orig\u0000?? test_vectors/\u0000?? utils/align.py.orig\u0000?? utils/io.py.orig\u0000",
  "firmware_name": "econ-mezz-tester-kria.bit\u0000",
  "firmware_git_desc": "9e5953f-dirty",
  "chip_number": null
}